#!/usr/bin/env bash
# Install a dev-mode `habitui` shim into the user's PATH.
#
# After running this once, every time you type `habitui` in a terminal,
# cargo will incrementally recompile from this checkout and run the fresh
# binary — no manual `cargo install` after each edit.
#
# For end users who installed via `cargo install --git ...` this script is
# irrelevant; their `habitui` is a real compiled binary in ~/.cargo/bin.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/.." &>/dev/null && pwd)"
MANIFEST="$PROJECT_ROOT/Cargo.toml"

if [[ ! -f "$MANIFEST" ]]; then
    echo "error: could not find Cargo.toml at $MANIFEST" >&2
    exit 1
fi

# Pick a destination on PATH. Prefer ~/.cargo/bin (already on PATH for any
# cargo user) and fall back to ~/.local/bin.
if [[ -d "$HOME/.cargo/bin" ]]; then
    BIN_DIR="$HOME/.cargo/bin"
elif [[ -d "$HOME/.local/bin" ]]; then
    BIN_DIR="$HOME/.local/bin"
else
    mkdir -p "$HOME/.local/bin"
    BIN_DIR="$HOME/.local/bin"
fi
TARGET="$BIN_DIR/habitui"

cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# habitui dev shim — auto-generated by scripts/dev-link.sh.
# Rebuilds incrementally from $PROJECT_ROOT and runs the fresh binary.
exec cargo run --quiet --release --manifest-path "$MANIFEST" -- "\$@"
EOF
chmod +x "$TARGET"

echo "Installed dev shim at $TARGET"
echo "Source: $MANIFEST"
echo
echo "Try it: habitui"
echo "To remove: rm $TARGET   (then 'cargo install --path .' to reinstall a static binary)"
